### ISSUE TITLE
perl: symbol lookup error

### ISSUE THREAD

**Issue by relyanow** [aquaskyline/LRSIM#1]
When I run test.sh I get:

perl: symbol lookup error: ./lib/auto/Math/Random/Random.so: undefined symbol: Perl_Gthr_key_ptr

I am using perl version v5.20.2

**Comment by aquaskyline** [comment]
This usually happens when your perl version is mismatched with modules. Please try removing the 'lib' folder, and install Perl Inline::C module directly in your system. You can find the module here: http://search.cpan.org/~ingy/Inline-C-0.76/lib/Inline/C.pod
