### ISSUE TITLE
request: don't generate structural variants by default 

### ISSUE THREAD

**Issue by benvvalk** [aquaskyline/LRSIM#10]
Thanks for developing this great tool!

IMO, LRSIM should not generate reads with synthetic structural variants by default -- that is likely a surprising behaviour for end users.

For example, I was doing some evaluation of assembly algorithms with LRSIM reads and eventually found out that some of the disagreements were caused by the LRSIM reads and not by the assembler.

**Comment by aquaskyline** [comment]
@benvvalk thanks for the suggestion, would you mind share more about the disagreements caused by the synthetic structural variants, what are they?

**Comment by benvvalk** [comment]
Hi @aquaskyline,

I didn't examine the misassemblies closely. I just noticed that, unsurprisingly, the number of misassemblies reported by QUAST went down once the LRSIM options for generating synthetic variants were set to zero.

Specifically, I am suggesting that it would be less surprising for end users if the following options had a default value of 0:
```
	-1 INT      1 SNP per INT base pairs [1000]
	-4 INT      # of Indels  [1000]
	-7 INT      # of Duplications and # of Inversions [100]
	-0 INT      # of Translocations [100]
```

**Comment by aquaskyline** [comment]
added option -n to disable all SVs

**Comment by benvvalk** [comment]
Thanks @aquaskyline!
