### ISSUE TITLE
both reads 1 and 2 have "/1" suffix 

### ISSUE THREAD

**Issue by benvvalk** [aquaskyline/LRSIM#11]
Just a small bug I noticed.

The LRSIM output read names have the suffix "/1", for both read 1 and read 2 in a pair.  This could potentially confuse downstream tools.

**Comment by aquaskyline** [comment]
Thanks for reporting, this is a bug and I will fix it soon.

**Comment by benvvalk** [comment]
Thank you, @aquaskyline!
