### ISSUE TITLE
Can't locte Math/Random.pm

### ISSUE THREAD

**Issue by mossishahi** [aquaskyline/LRSIM#24]
Hi
As I was taking the steps to install LRSIM, faced the below error while running the `sh test.sh`. 

```
Can't locate Math/Random.pm in @INC (you may need to install the Math::Random module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ../simulateLinkedReads.pl line 35.
BEGIN failed--compilation aborted at ../simulateLinkedReads.pl line 35.
```
un commented these two lines:
```
#use lib "./lib";
#use lib dirname($0)."/lib";
```
but was not helpful and faced this error:

then deleted the `lib` folder and did the recommended steps in #1 , but was faced the same errors.

**Comment by aquaskyline** [comment]
Please install the Perl library Math::Random in your system. Usually it is installed by default with Perl
