### ISSUE TITLE
Barcode issue in few-molecules case

### ISSUE THREAD

**Issue by sinamajidian** [aquaskyline/LRSIM#25]
Dear respected LRSIM team
Thanks for your great package, I'm using LRSIM to generate linked reads for a small genome. I used the following

`simulateLinkedReads.pl -g hap1.fa,hap2.fa,hap3.fa  -p out/sim -o -n -x 1 -f 100 -m 3 -t 1`

It works. But, I think it there is a problem in LRSIM's output. It seems that each haplotype are considered separately.  By setting -m 3, in each partition, three molecules originates from a haplotype. But, in a real 10x device, each of three molecules may come from different haplotypes. 
This can be interfered from the manifest file. There is no shared barcode within manifests correspond to haplotypes. 

Would you please tell me whether I am right or not? If yes, It will be appreciated if you tell me how I can overcome this issue.

**Comment by aquaskyline** [comment]
A solution is to concatenate multiple haps with a 100k N gap into a single FASTA.

**Comment by sinamajidian** [comment]
Thanks.
Another idea can be concatenating all haplotypes in a new fasta file `cat hap1.fa hap2.fa hap3.fa > genome.fa`. So, haplotypes in `genome.fa` are separated by `>fa_id`.  It seems that it's working!
