### ISSUE TITLE
time

### ISSUE THREAD

**Issue by mossishahi** [aquaskyline/LRSIM#26]
Hi

we are testing LRSIM for to generate 10X reads for an organism with genome size about 1.5Gbp. As I was noticed, you had mentioned that the normal time for a genome like human genome will take a time less than 10 hours. But it is 283 hours we are running the LRSIM on 16 threads and about 160 GB memory. 

is it abnormal? do you recommend to stop it?

**Comment by aquaskyline** [comment]
Please stop. It's because LRSIM was running out of available barcodes (about 4M available in total) for your setting combination.

**Comment by mossishahi** [comment]
@aquaskyline thanks. So what should we do? what are the options to extend the number of barcodes?

**Comment by aquaskyline** [comment]
Could you please show me your setting and the size of your genome input?

**Comment by mossishahi** [comment]
@aquaskyline thanks.
I have run LRSIM using this command : 
```
../../Apps/LRSIM/simulateLinkedReads.pl -r /mnt/hdd2/mostafa/Bio-Mostafa/data/Dj_genome_v1.fasta -p SimulatedReads -z 16
```
- we are trying to have an assembly using 10X technology for a genome which its estimated genome size is about 1.5Gbp and it is repetitive regions which makes assembly process hard. 

my other question is about the outputs of LRSIM. Does LRSIM do some analysis about our genome including the ideal coverage we should have in genome assembly or even some other statistics?
or it only makes a 10X library for us to do an assembly process using an assembler?

**Comment by aquaskyline** [comment]
No, LRSIM won't analyze the characteristic of your input. It outputs exactly as you set in the parameters.

Do you know which step LRSIM was stuck at? You could run "ls -lrt" at the folder your ran LRSIM, and paste the outputs in your reply. That helps to narrow the problem.

**Comment by mossishahi** [comment]
@aquaskyline 
```
drwxrwxrwx 1 root root          0 ﻑﻭﺭیﻩ  6 17:38 _Inline
-rwxrwxrwx 1 root root        647 ﻑﻭﺭیﻩ  6 17:38 SimulatedReads.hap.parameter
-rwxrwxrwx 2 root root 1205168252 ﻑﻭﺭیﻩ  6 18:26 SimulatedReads.hapA.fasta
-rwxrwxrwx 2 root root 1205168252 ﻑﻭﺭیﻩ  6 18:26 SimulatedReads.hap.0.fasta
-rwxrwxrwx 2 root root 1205223004 ﻑﻭﺭیﻩ  6 18:26 SimulatedReads.hapB.fasta
-rwxrwxrwx 2 root root 1205223004 ﻑﻭﺭیﻩ  6 18:26 SimulatedReads.hap.1.fasta
-rwxrwxrwx 1 root root      12809 ﻑﻭﺭیﻩ  6 18:26 SimulatedReads.hap.hetA.insertions.fa
-rwxrwxrwx 1 root root   18563387 ﻑﻭﺭیﻩ  6 18:26 SimulatedReads.hap.hetA.bed
-rwxrwxrwx 1 root root      12546 ﻑﻭﺭیﻩ  6 18:26 SimulatedReads.hap.hetB.insertions.fa
-rwxrwxrwx 1 root root   18574133 ﻑﻭﺭیﻩ  6 18:26 SimulatedReads.hap.hetB.bed
-rwxrwxrwx 1 root root      11316 ﻑﻭﺭیﻩ  6 18:26 SimulatedReads.hap.homAB.insertions.fa
-rwxrwxrwx 1 root root   18545140 ﻑﻭﺭیﻩ  6 18:26 SimulatedReads.hap.homAB.bed
-rwxrwxrwx 1 root root 1210279064 ﻑﻭﺭیﻩ  6 18:27 SimulatedReads.hap.0.clean.fasta
-rwxrwxrwx 1 root root 1210334079 ﻑﻭﺭیﻩ  6 18:27 SimulatedReads.hap.1.clean.fasta
-rwxrwxrwx 1 root root    1455863 ﻑﻭﺭیﻩ  6 18:27 SimulatedReads.hap.0.clean.fasta.fai
-rwxrwxrwx 1 root root    1455867 ﻑﻭﺭیﻩ  6 18:27 SimulatedReads.hap.1.clean.fasta.fai
-rwxrwxrwx 1 root root 1215160320 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.0.0.12.fastq
-rwxrwxrwx 1 root root 1215168512 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.0.2.12.fastq
-rwxrwxrwx 1 root root 1215160320 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.0.3.12.fastq
-rwxrwxrwx 1 root root 1215172608 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.0.5.12.fastq
-rwxrwxrwx 1 root root 1215164416 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.0.4.12.fastq
-rwxrwxrwx 1 root root 1215164416 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.0.6.12.fastq
-rwxrwxrwx 1 root root 1215537152 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.1.0.12.fastq
-rwxrwxrwx 1 root root 1215160320 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.0.1.12.fastq
-rwxrwxrwx 1 root root 1215541248 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.1.2.12.fastq
-rwxrwxrwx 1 root root 1215541248 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.1.1.12.fastq
-rwxrwxrwx 1 root root 1215541248 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.1.3.12.fastq
-rwxrwxrwx 1 root root 1215164416 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.0.7.12.fastq
-rwxrwxrwx 1 root root 1215541248 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.1.6.12.fastq
-rwxrwxrwx 1 root root 1215541248 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.1.4.12.fastq
-rwxrwxrwx 1 root root 1215541248 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.1.5.12.fastq
-rwxrwxrwx 1 root root 1215541248 ﻑﻭﺭیﻩ  6 18:34 SimulatedReads.dwgsim.1.7.12.fastq
-rwxrwxrwx 1 root root       6367 ﻑﻭﺭیﻩ 20 00:50 SimulatedReads.status
-rwxrwxrwx 1 root root          0 ﻑﻭﺭیﻩ 22 09:17 command.txt
```
should we specify another parameter for running the process?

**Comment by aquaskyline** [comment]
Were you running out of disk space?

By the way, please use "-t 750 and -z 4".

**Comment by mossishahi** [comment]
@aquaskyline  no there is much free space. Ok

**Comment by mossishahi** [comment]
@aquaskyline 
Hi
we have launched the LSRIM using a command as you said. 
it is running for 28 hours till now and I think it should take this much time. 
do you suggest to keep it running?

**Comment by mossishahi** [comment]
@aquaskyline the last log I have observerd is:
```
DjScaffold99999 length: 12205
38203 sequences, total length: 1192678067
Currently On: 7057813
```  
and is stuck here!

**Comment by aquaskyline** [comment]
That's weird, could you please attach the full log?

**Comment by mossishahi** [comment]
@aquaskyline Sorry, Since I had no idea how to copy logs from a running a process, [here](https://drive.google.com/file/d/1q2Y6Bdl3LI1r3BU-nUCNi8jRIRfLPQA4/view?usp=sharing) are the screenshots available from this process.

**Comment by smajidian** [comment]
Th log file is in the output folder with ".status" extension.

**Comment by smajidian** [comment]
@mossishahi The full log is in this file "SimulatedReads.status".

**Comment by aquaskyline** [comment]
it seems to me that your genome input is an assembly and it's too fragmented, with most of the scaffolds at 10s of kilobases. 10x Genomics uses an average of 100kbp fragment size, which is longer than most of the scaffolds. LRSIM requires scaffolds longer than the fragment size for reads simulation. LRSIM will soon run out of usable scaffolds if most of the scaffolds are shorter than the fragment size. You might have to improve your assembly contiguity first.
