### ISSUE TITLE
Increased read depth flanking N-stetches in reference

### ISSUE THREAD

**Issue by WURBrian** [aquaskyline/LRSIM#27]
Based on a reference genome, I simulated haplotypes using a different algorithme. Using these haplotypes as input, I used LRSIM to simulate 10x data using the command:

simulateLinkedReads.pl -g DMsim1.hap.0.clean.fasta,DMsim1.hap.1.clean.fasta,DMsim1.hap.2.clean.fasta,DMsim1.hap.3.clean.fasta -p DMsim1 -x 100 -f 20 -u 3 -z 4 -o

But, when mapping the reads of the simulated 10x dataset to the reference genome, I noticed an increased read dept on the left side of all N-stretches of my reference genome.

![image](https://user-images.githubusercontent.com/7846241/53956873-20938680-40dd-11e9-832e-42e4b90f4b7b.png)

**Comment by aquaskyline** [comment]
This is interesting, would longer N-stretches help?
