### ISSUE TITLE
Few SNPs generated using two haplotype sequence

### ISSUE THREAD

**Issue by pxulab** [aquaskyline/LRSIM#28]
Hi there, 

I use two haplotype fasta sequences as input to simulate 10X linked reads in human genome. By default, it should output 3M SNPs because -1 parameter (1 SNP per INT base pairs [1000]). But I only got ~10k SNPs. Could you help to figure out the problem? The command I used is below: 
 ```
./simulateLinkedReads.pl -g hap1_genome.fa,hap2_genome.fa -p HG002_sim -7 0 -0 0
```

Best, 
Peng Xu

**Comment by aquaskyline** [comment]
if you use -g, no variant will be simulated. Please use -r if you need variant simulation.
