### ISSUE TITLE
LRSIM phase4 problem

### ISSUE THREAD

**Issue by cbirbes** [aquaskyline/LRSIM#32]
Hi, i tried to simulate 10X reads from a 20MB sequence with :

perl ../simulateLinkedReads.pl -g fastaOriginal.fasta -p OutputLRSIM/default_params -b ../4M-with-alts-february-2016.txt -n -x 1 -f 150 -t 1 -m 3 -o -u 4

and with the test files.
Phase 1 2 and 3 run well, but phase 4 stop at the end :
```
Thu Oct 17 14:02:47 2019: Simulate reads start
Thu Oct 17 14:02:47 2019: Load barcodes start
Thu Oct 17 14:02:48 2019: Load barcodes end
Thu Oct 17 14:02:48 2019: Using fragment sizes from fragmentSizesList instead of Poisson distribution
Thu Oct 17 14:02:48 2019: 10000 sizes loaded
Thu Oct 17 14:02:48 2019: Average fragment size: 50kbp
Thu Oct 17 14:02:48 2019: readPairsPerMolecule: 100
Thu Oct 17 14:02:48 2019: Simulating on haplotype: 0
Thu Oct 17 14:02:48 2019: Load read positions haplotype 0
Thu Oct 17 14:02:48 2019: 0 reads failed being loaded.
Thu Oct 17 14:02:48 2019: Exporting ./test1.0.fp
Thu Oct 17 14:02:48 2019: Exported ./test1.0.fp
Thu Oct 17 14:02:48 2019: readsCountDown: 500000
Thu Oct 17 16:46:22 2019: Reached end of barcodes list. No more barcodes. Last read processed: 500000. Exiting.
Inappropriate ioctl for device at ../simulateLinkedReads.pl line 748.
```

How can i fix this problem please ? the software is well installed  (sh make.sh end with "Done, please run 'perl simulateLinkedReads.pl'")

**Comment by aquaskyline** [comment]
the prompt `inappropriate ioctl` might indicate some files are corrupted, please clone the repo again and check especially the "4M-with-alts-february-2016.txt" file to ensure it's not empty.
