### ISSUE TITLE
Extension to BGI stLFR

### ISSUE THREAD

**Issue by Ellis-Anderson** [aquaskyline/LRSIM#33]
Hello,

I was wondering if it would be possible and if there were any plans, to extend this simulation software to model stLFR linked reads as well? I think that biggest difference is generally in the number of molecules per barcode. stLFR averages around 1.2 or so. Please let me know if I can get you anymore information on stLFR and if this could potentially be an added feature.

Best,
Ellis

**Comment by mschatz** [comment]
We are not planing to add this. It might be possible to approximate the characteristics by tuning average number of molecules per partition (-m) or the number of partitions (-t). I also see that BGI has a stLFR simulator in development: https://github.com/BGI-Qingdao/stLFR_reads_sim

Good luck!
Mike
