### ISSUE TITLE
Reported read positions appear to be offset

### ISSUE THREAD

**Issue by arshajii** [aquaskyline/LRSIM#4]
For example, one of my simulated reads is

<pre>
@chr1_198003258_198003034_1_0_0_0_0:0:0_0:0:0_0/1 1:N:0:1
AGAACAAGTCTCTATTGGCCAACATCTGGACAGCTTGTAGTTGAGCTGAATATGCTGCTGTGTGAATTACAAAGGTATGACAAATTTTTTACTCTGTTCTAATTTGGCTCGGCCTGCCTGCCTTCAGCTTTTTTGGCACAGCTTCCCACAT
+
AAAFFFKKKKKKKKKKFIIHGGFHFFFHGEFGEBAEFCACECACCCCCCCBFBBBCBCE?B=B=@?D>ADAAB@@@>@?ABBBCB@@B>?C@??D?@?A@B???A=AA?=><=>??>??>@>@?>>@@=?>?=??;==>?8>><===>??;
</pre>

which yields the alignments (using the SNAP aligner):

<pre>
chr1_198003258_198003034_1_0_0_0_0:0:0_0:0:0_0:AGAACAAGTCTCTATT	163	chr1	197999799	70	151=	=	198000023	352	GTGTCCTAGAGAAGCAGACTCAAATAACAAATCCCTGTGTAACTGCAAAGGTTTATACAAAGTGGCATTCCATGCAGAGTAGAGAATATGATGTAAAGAGCCATCAAACATTATGAGATCCCTCCCCTGCAGCACATAAACAAAGTGAGGT	IIHIFGFFHDFFFDGFCECDCCDDEDBCDBBBDCCBABBBBBEBDBE?A@EAAA@AA@@B?B=A@?@A@@E@??C@@AA@==?A??=??>>?>@A@@=<AA@=?9=?=?>?=>>@B>B>>>>>?<>@C?>@?@=<@=>=?9??=>=<=>>?	PG:Z:SNAP	NM:i:0	RG:Z:FASTQ	PL:Z:Illumina	PU:Z:pu	LB:Z:lb	SM:Z:sm
chr1_198003258_198003034_1_0_0_0_0:0:0_0:0:0_0:AGAACAAGTCTCTATT	83	chr1	198000023	70	128=	=	197999799	-352	ATGTGGGAAGCTGTGCCAAAAAAGCTGAAGGCAGGCAGGCCGAGCCAAATTAGAACAGAGTAAAAAATTTGTCATACCTTTGTAATTCACACAGCAGCATATTCAGCTCAACTACAAGCTGTCCAGAT	;??>===<>>8?>==;??=?>?=@@>>?@>@>??>??>=<>=?AA=A???B@A?@?D??@C?>B@@BCBBBA?@>@@@BAADA>D?@=B=B?ECBCBBBFBCCCCCCCACECACFEABEGFEGHFFFH	PG:Z:SNAP	NM:i:0	RG:Z:FASTQ	PL:Z:Illumina	PU:Z:pu	LB:Z:lb	SM:Z:sm
</pre>

However, these alignments are both offset by 3235 (and I have checked that there are no secondary alignments at the reported positions). All the other reads also seem to be offset by various amounts relative to the reported true positions.

**Comment by aquaskyline** [comment]
The offset in the read id is referring to the two new fasta references generated by SURVIVOR.

**Comment by arshajii** [comment]
Is there a straightforward way to translate the positions in the read identifiers to those in the original FASTA (i.e. hg19)? I am looking to do this in order to judge alignment accuracy. The alternative would be to look at the distance between mates, which (as far as I can tell) should be equal for both sets of positions if the alignments are accurate. This could still produce false positives, however.

Again, thanks for your help and prompt replies.

**Comment by aquaskyline** [comment]
I suggest you to use -d 1 -2 0 -3 0 -4 0 -5 0 -6 0 -7 0 to enable haplotype simulation mode and disable simulating unbalanced structural variants.

**Comment by arshajii** [comment]
Alright, that seems like the best solution -- thanks.
