### ISSUE TITLE
Install error - cannot find -lcurses

### ISSUE THREAD

**Issue by stephenwilliams22** [aquaskyline/LRSIM#5]
when I run sh make.sh I get this error. any suggestions?

```make[2]: Leaving directory `/mnt/home/stephen/Apps/LRSIM/DWGSIMSrc/samtools/misc'
gcc -g -Wall -O3  -o samtools bam_tview.o bam_plcmd.o sam_view.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o kaln.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o bam_tview_curses.o bam_tview_html.o  libbam.a -Lbcftools -lbcf  -lcurses  -lm -lz -lpthread
/mnt/home/stephen/.linuxbrew/bin/ld: cannot find -lcurses
collect2: error: ld returned 1 exit status
make[1]: *** [samtools] Error 1
make[1]: Leaving directory `/mnt/home/stephen/Apps/LRSIM/DWGSIMSrc/samtools'
make: *** [all-recur] Error 1```

Also FYI, the first step of the install should be cd LRSIM not cd 10xReadsSimulator

**Comment by aquaskyline** [comment]
you need to install the 'ncurses' library.

You can get more details on installing the library here:
https://www.cyberciti.biz/faq/linux-install-ncurses-library-headers-on-debian-ubuntu-centos-fedora/

Please notice that you need root to install a new library. If you are using a shared computing grid, you might wanna write to the administrators.

**Comment by stephenwilliams22** [comment]
Thanks for the reply; however, ncurses is installed as root. I have samtools installed as well and this is where the error seems to be coming from. Any other ideas?  Can I point LRSIM to my installed version of samtools?

**Comment by stephenwilliams22** [comment]
Thanks, I believe this fixed it.
