### ISSUE TITLE
msort: error: use of undeclared identifier 'direct_insert_aux'

### ISSUE THREAD

**Issue by sjackman** [aquaskyline/LRSIM#6]
I see the following error when compiling `msort` with both `g++-7` and `clang++`:
```
clang++    -c -o stdhashc.o stdhashc.cc
In file included from stdhashc.cc:2:
./stdhash.hh:496:13: error: use of undeclared identifier 'direct_insert_aux'
                int ret = direct_insert_aux(key, this->n_capacity, this->keys, this->flags, &i);
                          ^
                          this->
stdhashc.cc:72:34: note: in instantiation of member function 'hash_map_misc<unsigned int, int>::insert' requested here
        return ((hashii_cpp_t*)h->ptr)->insert(key, value);
                                        ^
./stdhash.hh:295:13: note: must qualify identifier to find this declaration in dependent base class
        inline int direct_insert_aux(const keytype_t &key, hashint_t m, keytype_t *K, __lh3_flag_t *F, hashint_t *i) {
                   ^
1 error generated.
```
See the full log here: https://gist.github.com/sjackman/d4de672ec5f8a44f5276cef9edf9a28f#file-02-make-L12

**Comment by sjackman** [comment]
I see the same error with `g++-7`.

**Comment by sjackman** [comment]
With `g++-7`:
```
g++-7    -c -o stdhashc.o stdhashc.cc
In file included from stdhashc.cc:2:0:
stdhash.hh: In instantiation of 'bool hash_map_misc<keytype_t, valtype_t>::insert(const keytype_t&, const valtype_t&) [with keytype_t = unsigned int; valtype_t = int]':
stdhashc.cc:72:51:   required from here
stdhash.hh:496:30: error: 'direct_insert_aux' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   int ret = direct_insert_aux(key, this->n_capacity, this->keys, this->flags, &i);
```

**Comment by sjackman** [comment]
Compiling with `g++-7 -fpermissive` did work, as the above error suggested. This doesn't help `clang++` though on macOS. A fix for compiling on macOS with `clang++` would be awesome.

**Comment by aquaskyline** [comment]
clang doesn't support -fpermissive. One handy solution is to install gcc in MacOS using homebrew.

**Comment by sjackman** [comment]
Yeah, that's the workaround that I've gone with. I'd like to submit a Homebrew formula for `lrsim` to Homebrew-Science. It would be helpful if it could be compiled with `clang`. If not, I can say that it `fails_with :clang`.

**Comment by aquaskyline** [comment]
Allowing pointers to overlap is actually a trick used in msort, removing this behavior will change the algorithm and probably slow down the algorithm. Is the gcc workaround looks good and clean to you? If not I can swap msort with gnusort, in trade of running speed though.

**Comment by sjackman** [comment]
Ah, I see. Yes, using `gcc` is a reasonable workaround in that case. It's good to know that GNU `sort` can be used as a replacement for `msort`.
