### ISSUE TITLE
Supernova failing with Simulated data

### ISSUE THREAD

**Issue by lcoombe** [aquaskyline/LRSIM#9]
Hello,

I have simulated some human chromium data using LRSIM, and while I can run longranger basic fine, Supernova is failing.

Here's the error in the main log: 
```
2017-09-13 23:26:37 [runtime] (failed)          ID.GRCh38_LRSIM_supernova.ASSEMBLER_CS._ASSEMBLER.ASSEMBLER_DF

[error] An unexpected error has occurred.

Saving pipestance info to GRCh38_LRSIM_supernova/GRCh38_LRSIM_supernova.mri.tgz
```

And here's the error in the ASSEMBLER_DF stdout log:
```
Wed Sep 13 11:25:51 2017: reading in paths --> pathsX, mem = 11.98 GB
ForceAssertGe(numReads,0) at src/10X/paths/ReadPathVecX.cc:295 failed in function
void ReadPathVecX::reserve(int64_t, int64_t)
wwith values arg1 = -2 and arg2 = 0
ForceAssertGe(numReads,0) at src/10X/paths/ReadPathVecX.cc:295 failed in function
void ReadPathVecX::reserve(int64_t, int64_t)
wwith values arg1 = -2 and arg2 = 0
ForceAssertGe(numReads,0) at src/10X/paths/ReadPathVecX.cc:295 failed in function
void ReadPathVecX::reserve(int64_t, int64_t)
with values arg1 = -6 and arg2 = 0
```

Just wondering if you have seen this error when running Supernova with the simulated data, and if you know what is causing this failure?

**Comment by aquaskyline** [comment]
I'm confused, the problem seems to relate to the command line you ran Supernova.

**Comment by lcoombe** [comment]
Hello,
So I've run Supernova successfully a number of times previously using real data, but I see this error when I try to use the simulated data. I contacted 10xGenomics Support, and they suspect that it was something about the simulated data that caused the issue:
"This particular error is telling us that somewhere in the code, supernova expected there to be at least 1 read present for some calculation, but it didn't find any."
They suspected that it was something to do with the input simulated data that lead to the failure. 
I had seen another github issue where Longranger align was failing when using LRSIM-simulated data, so I was wondering if you had any suggestions for why the simulated data could be causing the Supernova failure.

NOTE: I simulated the reads using the command:
`perl simulateLinkedReads.pl -r human-reference.fa -p GRCh38_LRSIM -4 0 -7 0 -0 0`

Thanks,
Lauren

**Comment by aquaskyline** [comment]
Hi Lauren,

This seems to be a contingent bug in LRSIM or might be due to the latest modifications in Supernova. Would you mind share me the GRCh38_LRSIM_supernova.mri.tgz file so I could get a better feeling on what Supernova is complaining about.

**Comment by lcoombe** [comment]
Of course - it is OK with you if I e-mail it to you at aquaskyline@gmail.com? 
(I just don't know what information it stores in those files, so would prefer to just share with you)

**Comment by aquaskyline** [comment]
yes, please send it to aquaskyline@gmail.com

**Comment by lcoombe** [comment]
Thanks - just sent it to you.

**Comment by aquaskyline** [comment]
Quote from your error messages:
```
Wed Sep 13 11:14:15 2017: pathing iteration 81 of 86
Wed Sep 13 11:14:52 2017: pathing iteration 82 of 86
Wed Sep 13 11:15:27 2017: pathing iteration 83 of 86
Wed Sep 13 11:16:01 2017: pathing iteration 84 of 86
Wed Sep 13 11:16:36 2017: pathing iteration 85 of 86
Wed Sep 13 11:17:11 2017: pathing iteration 86 of 86
Wed Sep 13 11:25:02 2017: done pathing reads
after_msp_path: mem = 99.65 GB, peak = 153.46 GB
Wed Sep 13 11:25:16 2017: back from buildReadQGraph
Wed Sep 13 11:25:16 2017: memory in use = 11.60 GB, peak = 153.46 GB
N50 edge length = 1115
Wed Sep 13 11:25:51 2017: reading in paths --> pathsX, mem = 11.98 GB
ForceAssertGe(numReads,0) at src/10X/paths/ReadPathVecX.cc:295 failed in function
void ReadPathVecX::reserve(int64_t, int64_t)
wwith values arg1 = -2 and arg2 = 0
ForceAssertGe(numReads,0) at src/10X/paths/ReadPathVecX.cc:295 failed in function
void ReadPathVecX::reserve(int64_t, int64_t)
wwith values arg1 = -2 and arg2 = 0
ForceAssertGe(numReads,0) at src/10X/paths/ReadPathVecX.cc:295 failed in function
void ReadPathVecX::reserve(int64_t, int64_t)
with values arg1 = -6 and arg2 = 0

Wed Sep 13 23:26:34 2017.  Abort.  Stopping.

Generating a backtrace...
ForceAssertGe(numReads,0) at src/10X/paths/ReadPathVecX.cc:295 failed in function
void ReadPathVecX::reserve(int64_t, int64_t)
with values arg1 = -8 and arg2 = 0
bytes in use before   :              32,464,699,392
theoretical max bytes :           2,705,278,570,496
--------------------------------------------------------------------------------
DETAILED MEMORY STATS
```

The Supernova's DF has already built a graph on the data and iterated through the graph multiple times. So we can make sure that Supernova has indeed processed all the data LRSim has generated without problem. The error occurred when Supernova was processing a data structure generated by itself.

At this moment I think the problem is due to a marginal graph traversal or simplification case misconsidered by Supernova's code.

I have two solutions for you,
1) run LRSim again to generate another set of simulated data, change the parameters very slightly, say -t 1500 to 1499, that will be enough to change the output dataset entirely. Run Supernova again on the new dataset to see if it works.
2) use an older Supernova version, say 1.1.1. LRSim was tested with version 1.1.1 on multiple species and parameter settings.

Thanks,

**Comment by lcoombe** [comment]
Thank you for the suggestions!
Just to update on what worked, I tried with an older Supernova version (v1.1.1) as suggested, and was able to get a successful run. I also attempted the run with v1.2.0 and a different number of cores, and was able to get a successful run using 24 cores.

Thanks again!

**Comment by aquaskyline** [comment]
Cool~
